name: CI Workflow - Docker

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t task-manager:latest .

      # Step 3: Run the Docker container
      - name: Run Docker Container
        run: |
          docker run --rm -e GITHUB_USER="${{ github.actor }}" task-manager:latest

